import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./(components)/Navbar";
import { Toaster, toast } from 'sonner'; 
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <SidebarProvider defaultOpen={false}>
          <Navbar />
          <div className="flex">
            <AppSidebar />
            <SidebarInset>
              <main className="flex-1 p-4 mt-16">{children}</main>
              {/* <main className="max-w-7xl mx-auto mt-16 px-4 sm:px-6 lg:px-8">{children}</main> */}
            {/* </SidebarInset> */}
          {/* </div> */}
        {/* </SidebarProvider> */} 
        <Toaster />
        {children}
      </body>
    </html>
  );
}
